export const COUNTRY_USER = [
  {
    country: "USA",
    cities: [
      "New York",
      "Los Angeles",
      "Chicago",
      "Miami",
      "Las Vegas",
      "Seattle",
      "Houston",
    ],
  },
  {
    country: "United Kingdom",
    cities: [
      "London",
      "Manchester",
      "Liverpool",
      "Birmingham",
      "Edinburgh",
      "Glasgow",
      "Bristol",
    ],
  },
  {
    country: "Germany",
    cities: [
      "Berlin",
      "Munich",
      "Hamburg",
      "Cologne",
      "Frankfurt",
      "Stuttgart",
      "Düsseldorf",
    ],
  },
  {
    country: "France",
    cities: [
      "Paris",
      "Lyon",
      "Marseille",
      "Toulouse",
      "Nice",
      "Nantes",
      "Strasbourg",
    ],
  },
  {
    country: "Poland",
    cities: [
      "Warsaw",
      "Krakow",
      "Wroclaw",
      "Gdansk",
      "Poznan",
      "Lodz",
      "Katowice",
    ],
  },
  {
    country: "Ukraine",
    cities: [
      "Kyiv",
      "Lviv",
      "Kharkiv",
      "Odessa",
      "Dnipro",
      "Zaporizhzhia",
      "Vinnytsia",
    ],
  },
  {
    country: "Canada",
    cities: [
      "Toronto",
      "Vancouver",
      "Montreal",
      "Calgary",
      "Ottawa",
      "Edmonton",
      "Winnipeg",
    ],
  },
  {
    country: "Spain",
    cities: [
      "Madrid",
      "Barcelona",
      "Valencia",
      "Seville",
      "Zaragoza",
      "Malaga",
      "Murcia",
    ],
  },
];

export const POPULAR_PROFESSIONS = [
  "Frontend Developer",
  "Backend Developer",
  "Fullstack Developer",
  "UI/UX Designer",
  "Project Manager",
  "QA Engineer",
  "Sales Manager",
  "Data Scientist",
  "DevOps Engineer",
  "Marketing Specialist",
  "Mobile App Developer",
  "Cloud Architect",
  "Cybersecurity Analyst",
  "Data Analyst",
  "Product Manager",
  "System Administrator",
  "Network Engineer",
  "Database Administrator",
  "Machine Learning Engineer",
  "Technical Writer",
  "Graphic Designer",
  "Motion Designer",
  "3D Artist",
  "Video Editor",
  "Content Creator",
  "HR Manager",
  "Digital Marketing Manager",
  "Doctor",
  "Nurse",
  "Pharmacist",
  "Dentist",
  "Physical Therapist",
  "Accountant",
  "Financial Analyst",
  "Lawyer",
  "Teacher",
  "Professor",
  "Architect",
  "Civil Engineer",
  "Electrician",
] as const;
